version: "3"
services:
    web:
        build: .
        ports:
            - "8001:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Particulate42!"
            ACCEPT_EULA: "Y"